[MIG] base_technical_features: Migration to 18.0
Kimkhoi3010/server-ux pull request #2
Opened 2024-10-01 03:55 UTC by Kimkhoi3010

2024-10-01 07:49 UTC, nilshamerlinck commented on base_technical_features/models/base.py
> +    def user_has_groups(self, groups):
`user_has_groups` has been removed in 18: see `https://github.com/odoo/odoo/pull/151597`

2024-10-01 07:50 UTC, nilshamerlinck commented on base_technical_features/models/ir_ui_view.py
> +    def _postprocess_access_rights(self, tree):
an explanation of the new approach in the PR description would be welcome to help reviewer

2024-10-02 09:44 UTC, nguyenminhchien requested changes

2024-10-02 09:44 UTC, nguyenminhchien commented on base_technical_features/models/base.py
> +    def has_groups(self, groups):
this method should be in res.users and consider to override `def has_group()` or `def _has_group()`

2024-10-02 09:44 UTC, nguyenminhchien commented on base_technical_features/models/base.py
> +    def has_groups(self, groups):
this commit made me confused, these changes should be included in a migration commit

2024-10-02 09:44 UTC, nguyenminhchien commented on base_technical_features/models/ir_ui_view.py
> +    def _postprocess_access_rights(self, tree):
Overriding this method conflicts with the module `web_studio`

2024-10-02 10:26 UTC, nguyenminhchien commented on base_technical_features/models/ir_ui_view.py
> +    def _postprocess_access_rights(self, tree):
If you cannot find a better way. try this one 
```
    @api.model
    def _postprocess_access_rights(self, tree):
        arch = etree.tostring(tree, encoding="unicode").replace('\t', '').replace('base.group_no_one', 'base_technical_features.group_technical_features')
        tree = etree.fromstring(arch)
        return super()._postprocess_access_rights(tree)
        
```

2024-10-10 07:21 UTC, nguyenminhchien requested changes

2024-10-10 07:21 UTC, nguyenminhchien commented on base_technical_features/models/ir_ui_view.py
> +                    self.env.ref("base_technical_features.group_technical_features").id
@Kimkhoi3010 replace the string `base.group_no_one` by the string `base_technical_features.group_technical_features`.

NOT replace its `id` in database

2024-10-10 07:21 UTC, nguyenminhchien commented on base_technical_features/readme/CREDITS.md
> +- Camptocamp.
Just keep it as before: `The migration of this module from 17.0 to 18.0 was financially supported by Camptocamp.`

2024-10-10 07:21 UTC, nguyenminhchien commented on base_technical_features/tests/test_base_technical_features.py
> +        print("\n====", self.env.user.groups_id)
remove 2 print commands

2024-10-10 07:25 UTC, nguyenminhchien commented
seems that you cannot port this commit in https://github.com/OCA/server-ux/pull/411
so, add it to port blacklist by creating a new commit, include that new commit into this PR

2024-10-11 10:28 UTC, nguyenminhchien approved these changes

2024-10-15 04:05 UTC, closed without merging

2024-10-16 02:36 UTC, nilshamerlinck commented on base_technical_features/models/ir_ui_view.py
> +    def _postprocess_access_rights(self, tree):
still no explanation

2024-10-16 02:50 UTC, Kimkhoi3010 commented
I created a new PR [OCA#953](https://github.com/OCA/server-ux/pull/953) to OCA/server-ux.
(This PR was closed auto after rebased)